[project]
name = "mercuryproj"
version = "0.0.1"
authors = [
    { name="Do Won Kim", email="dowonkim@umd.edu" },
    { name="Giovanni Luca Ciampaglia", email="gciampag@umd.edu" },
    { name="Rivado Edah", email="redah@terpmail.umd.edu" },
    { name="Justin Pratama", email="jpratama@terpmail.umd.edu" },
    { name="Dhruva Rayasam", email="drayasam@terpmail.umd.edu" }
]
description = "Backend API and scripts for the 'Muting low-quality sources' project of the Mercury Project research consortium."
dependencies = [
    "flask",
    "click",
    "tweepy",
    "pandas",
    "requests",
    "requests-oauthlib",
    "platformdirs",
    "psycopg",
    "flask-cors",
    "gunicorn",
    "aiohttp",
    "async-lru",
    "oauthlib",
    "schedule",
    "gevent"
]
readme = "README.md"
requires-python = ">=3.10"
# classifiers = [
#    "Programming Language :: Python :: 3",
#    "License :: OSI Approved :: MIT License",
#    "Operating System :: OS Independent",
# ]

[project.urls]
Homepage = "https://github.com/CSDL-UMD/Mercury"
Issues = "https://github.com/CSDL-UMD/Mercury/issues"

[tool.setuptools]
# packages = ["mercuryproj"]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]

[project.scripts]
eligibility-run = "mercuryproj.eligibility:main"
pre-engagements-run = "mercuryproj.pre_engagements:main"
pre-engagements-parse-run = "mercuryproj.pre_engagements_parse:main"
post-engagements-run = "mercuryproj.post_engagements:main"
post-engagements-parse-run = "mercuryproj.post_engagements_parse:main"
post-endline-engagements-run = "mercuryproj.post_endline_engagements:main"
post-endline-engagements-parse-run = "mercuryproj.post_endline_engagements_parse:main"
post-endline-atonce-run = "mercuryproj.post_endline_at_once:main"
post-endline-atonce-parse-run = "mercuryproj.post_endline_at_once_parse:main"
muting-run = "mercuryproj.muting:main"
unmuting-run = "mercuryproj.unmuting:main"
compliance-run = "mercuryproj.compliance:main"
compliance-voluntary-run = "mercuryproj.compliance_voluntary:main"